package com.my.youtubewatchtime.view.sa;

import android.content.Intent;
import android.os.Bundle;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;

public class Video500Activity extends AppCompatActivity {
        private WebView webview1;
    private WebView webview2;
    private WebView webview3;
    private WebView webview4;
    private WebView webview5;
    private WebView webview6;
    private WebView webview7;
    private WebView webview8;
    private WebView webview9;
    private WebView webview10;
    private WebView webview11;
    private WebView webview12;
    private WebView webview13;
    private WebView webview14;
    private WebView webview15;
    private WebView webview16;
    private WebView webview17;
    private WebView webview18;
    private WebView webview19;
    private WebView webview20;
    private WebView webview21;
    private WebView webview22;
    private WebView webview23;
    private WebView webview24;
    private WebView webview25;
    private WebView webview26;
    private WebView webview27;
    private WebView webview28;
    private WebView webview29;
    private WebView webview30;
    private WebView webview31;
    private WebView webview32;
    private WebView webview33;
    private WebView webview34;
    private WebView webview35;
    private WebView webview36;
    private WebView webview37;
    private WebView webview38;
    private WebView webview39;
    private WebView webview40;
    private WebView webview41;
    private WebView webview42;
    private WebView webview43;
    private WebView webview44;
    private WebView webview45;
    private WebView webview46;
    private WebView webview47;
    private WebView webview48;
    private WebView webview49;
    private WebView webview50;
    private WebView webview51;
    private WebView webview52;
    private WebView webview53;
    private WebView webview54;
    private WebView webview55;
    private WebView webview56;
    private WebView webview57;
    private WebView webview58;
    private WebView webview59;
    private WebView webview60;
    private WebView webview61;
    private WebView webview62;
    private WebView webview63;
    private WebView webview64;
    private WebView webview65;
    private WebView webview66;
    private WebView webview67;
    private WebView webview68;
    private WebView webview69;
    private WebView webview70;
    private WebView webview71;
    private WebView webview72;
    private WebView webview73;
    private WebView webview74;
    private WebView webview75;
    private WebView webview76;
    private WebView webview77;
    private WebView webview78;
    private WebView webview79;
    private WebView webview80;
    private WebView webview81;
    private WebView webview82;
    private WebView webview83;
    private WebView webview84;
    private WebView webview85;
    private WebView webview86;
    private WebView webview87;
    private WebView webview88;
    private WebView webview89;
    private WebView webview90;
    private WebView webview91;
    private WebView webview92;
    private WebView webview93;
    private WebView webview94;
    private WebView webview95;
    private WebView webview96;
    private WebView webview97;
    private WebView webview98;
    private WebView webview99;
    private WebView webview100;
    private WebView webview101;
    private WebView webview102;
    private WebView webview103;
    private WebView webview104;
    private WebView webview105;
    private WebView webview106;
    private WebView webview107;
    private WebView webview108;
    private WebView webview109;
    private WebView webview110;
    private WebView webview111;
    private WebView webview112;
    private WebView webview113;
    private WebView webview114;
    private WebView webview115;
    private WebView webview116;
    private WebView webview117;
    private WebView webview118;
    private WebView webview119;
    private WebView webview120;
    private WebView webview121;
    private WebView webview122;
    private WebView webview123;
    private WebView webview124;
    private WebView webview125;
    private WebView webview126;
    private WebView webview127;
    private WebView webview128;
    private WebView webview129;
    private WebView webview130;
    private WebView webview131;
    private WebView webview132;
    private WebView webview133;
    private WebView webview134;
    private WebView webview135;
    private WebView webview136;
    private WebView webview137;
    private WebView webview138;
    private WebView webview139;
    private WebView webview140;
    private WebView webview141;
    private WebView webview142;
    private WebView webview143;
    private WebView webview144;
    private WebView webview145;
    private WebView webview146;
    private WebView webview147;
    private WebView webview148;
    private WebView webview149;
    private WebView webview150;
    private WebView webview151;
    private WebView webview152;
    private WebView webview153;
    private WebView webview154;
    private WebView webview155;
    private WebView webview156;
    private WebView webview157;
    private WebView webview158;
    private WebView webview159;
    private WebView webview160;
    private WebView webview161;
    private WebView webview162;
    private WebView webview163;
    private WebView webview164;
    private WebView webview165;
    private WebView webview166;
    private WebView webview167;
    private WebView webview168;
    private WebView webview169;
    private WebView webview170;
    private WebView webview171;
    private WebView webview172;
    private WebView webview173;
    private WebView webview174;
    private WebView webview175;
    private WebView webview176;
    private WebView webview177;
    private WebView webview178;
    private WebView webview179;
    private WebView webview180;
    private WebView webview181;
    private WebView webview182;
    private WebView webview183;
    private WebView webview184;
    private WebView webview185;
    private WebView webview186;
    private WebView webview187;
    private WebView webview188;
    private WebView webview189;
    private WebView webview190;
    private WebView webview191;
    private WebView webview192;
    private WebView webview193;
    private WebView webview194;
    private WebView webview195;
    private WebView webview196;
    private WebView webview197;
    private WebView webview198;
    private WebView webview199;
    private WebView webview200;
    private WebView webview201;
    private WebView webview202;
    private WebView webview203;
    private WebView webview204;
    private WebView webview205;
    private WebView webview206;
    private WebView webview207;
    private WebView webview208;
    private WebView webview209;
    private WebView webview210;
    private WebView webview211;
    private WebView webview212;
    private WebView webview213;
    private WebView webview214;
    private WebView webview215;
    private WebView webview216;
    private WebView webview217;
    private WebView webview218;
    private WebView webview219;
    private WebView webview220;
    private WebView webview221;
    private WebView webview222;
    private WebView webview223;
    private WebView webview224;
    private WebView webview225;
    private WebView webview226;
    private WebView webview227;
    private WebView webview228;
    private WebView webview229;
    private WebView webview230;
    private WebView webview231;
    private WebView webview232;
    private WebView webview233;
    private WebView webview234;
    private WebView webview235;
    private WebView webview236;
    private WebView webview237;
    private WebView webview238;
    private WebView webview239;
    private WebView webview240;
    private WebView webview241;
    private WebView webview242;
    private WebView webview243;
    private WebView webview244;
    private WebView webview245;
    private WebView webview246;
    private WebView webview247;
    private WebView webview248;
    private WebView webview249;
    private WebView webview250;
    private WebView webview251;
    private WebView webview252;
    private WebView webview253;
    private WebView webview254;
    private WebView webview255;
    private WebView webview256;
    private WebView webview257;
    private WebView webview258;
    private WebView webview259;
    private WebView webview260;
    private WebView webview261;
    private WebView webview262;
    private WebView webview263;
    private WebView webview264;
    private WebView webview265;
    private WebView webview266;
    private WebView webview267;
    private WebView webview268;
    private WebView webview269;
    private WebView webview270;
    private WebView webview271;
    private WebView webview272;
    private WebView webview273;
    private WebView webview274;
    private WebView webview275;
    private WebView webview276;
    private WebView webview277;
    private WebView webview278;
    private WebView webview279;
    private WebView webview280;
    private WebView webview281;
    private WebView webview282;
    private WebView webview283;
    private WebView webview284;
    private WebView webview285;
    private WebView webview286;
    private WebView webview287;
    private WebView webview288;
    private WebView webview289;
    private WebView webview290;
    private WebView webview291;
    private WebView webview292;
    private WebView webview293;
    private WebView webview294;
    private WebView webview295;
    private WebView webview296;
    private WebView webview297;
    private WebView webview298;
    private WebView webview299;
    private WebView webview300;
    private WebView webview301;
    private WebView webview302;
    private WebView webview303;
    private WebView webview304;
    private WebView webview305;
    private WebView webview306;
    private WebView webview307;
    private WebView webview308;
    private WebView webview309;
    private WebView webview310;
    private WebView webview311;
    private WebView webview312;
    private WebView webview313;
    private WebView webview314;
    private WebView webview315;
    private WebView webview316;
    private WebView webview317;
    private WebView webview318;
    private WebView webview319;
    private WebView webview320;
    private WebView webview321;
    private WebView webview322;
    private WebView webview323;
    private WebView webview324;
    private WebView webview325;
    private WebView webview326;
    private WebView webview327;
    private WebView webview328;
    private WebView webview329;
    private WebView webview330;
    private WebView webview331;
    private WebView webview332;
    private WebView webview333;
    private WebView webview334;
    private WebView webview335;
    private WebView webview336;
    private WebView webview337;
    private WebView webview338;
    private WebView webview339;
    private WebView webview340;
    private WebView webview341;
    private WebView webview342;
    private WebView webview343;
    private WebView webview344;
    private WebView webview345;
    private WebView webview346;
    private WebView webview347;
    private WebView webview348;
    private WebView webview349;
    private WebView webview350;
    private WebView webview351;
    private WebView webview352;
    private WebView webview353;
    private WebView webview354;
    private WebView webview355;
    private WebView webview356;
    private WebView webview357;
    private WebView webview358;
    private WebView webview359;
    private WebView webview360;
    private WebView webview361;
    private WebView webview362;
    private WebView webview363;
    private WebView webview364;
    private WebView webview365;
    private WebView webview366;
    private WebView webview367;
    private WebView webview368;
    private WebView webview369;
    private WebView webview370;
    private WebView webview371;
    private WebView webview372;
    private WebView webview373;
    private WebView webview374;
    private WebView webview375;
    private WebView webview376;
    private WebView webview377;
    private WebView webview378;
    private WebView webview379;
    private WebView webview380;
    private WebView webview381;
    private WebView webview382;
    private WebView webview383;
    private WebView webview384;
    private WebView webview385;
    private WebView webview386;
    private WebView webview387;
    private WebView webview388;
    private WebView webview389;
    private WebView webview390;
    private WebView webview391;
    private WebView webview392;
    private WebView webview393;
    private WebView webview394;
    private WebView webview395;
    private WebView webview396;
    private WebView webview397;
    private WebView webview398;
    private WebView webview399;
    private WebView webview400;
    private WebView webview401;
    private WebView webview402;
    private WebView webview403;
    private WebView webview404;
    private WebView webview405;
    private WebView webview406;
    private WebView webview407;
    private WebView webview408;
    private WebView webview409;
    private WebView webview410;
    private WebView webview411;
    private WebView webview412;
    private WebView webview413;
    private WebView webview414;
    private WebView webview415;
    private WebView webview416;
    private WebView webview417;
    private WebView webview418;
    private WebView webview419;
    private WebView webview420;
    private WebView webview421;
    private WebView webview422;
    private WebView webview423;
    private WebView webview424;
    private WebView webview425;
    private WebView webview426;
    private WebView webview427;
    private WebView webview428;
    private WebView webview429;
    private WebView webview430;
    private WebView webview431;
    private WebView webview432;
    private WebView webview433;
    private WebView webview434;
    private WebView webview435;
    private WebView webview436;
    private WebView webview437;
    private WebView webview438;
    private WebView webview439;
    private WebView webview440;
    private WebView webview441;
    private WebView webview442;
    private WebView webview443;
    private WebView webview444;
    private WebView webview445;
    private WebView webview446;
    private WebView webview447;
    private WebView webview448;
    private WebView webview449;
    private WebView webview450;
    private WebView webview451;
    private WebView webview452;
    private WebView webview453;
    private WebView webview454;
    private WebView webview455;
    private WebView webview456;
    private WebView webview457;
    private WebView webview458;
    private WebView webview459;
    private WebView webview460;
    private WebView webview461;
    private WebView webview462;
    private WebView webview463;
    private WebView webview464;
    private WebView webview465;
    private WebView webview466;
    private WebView webview467;
    private WebView webview468;
    private WebView webview469;
    private WebView webview470;
    private WebView webview471;
    private WebView webview472;
    private WebView webview473;
    private WebView webview474;
    private WebView webview475;
    private WebView webview476;
    private WebView webview477;
    private WebView webview478;
    private WebView webview479;
    private WebView webview480;
    private WebView webview481;
    private WebView webview482;
    private WebView webview483;
    private WebView webview484;
    private WebView webview485;
    private WebView webview486;
    private WebView webview487;
    private WebView webview488;
    private WebView webview489;
    private WebView webview490;
    private WebView webview491;
    private WebView webview492;
    private WebView webview493;
    private WebView webview494;
    private WebView webview495;
    private WebView webview496;
    private WebView webview497;
    private WebView webview498;
    private WebView webview499;
    private WebView webview500;
    private String link = "";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video500);
        initializeViews();
        loadVideos();
    }

    private void initializeViews() {
                webview1 = findViewById(R.id.webview1);
        webview2 = findViewById(R.id.webview2);
        webview3 = findViewById(R.id.webview3);
        webview4 = findViewById(R.id.webview4);
        webview5 = findViewById(R.id.webview5);
        webview6 = findViewById(R.id.webview6);
        webview7 = findViewById(R.id.webview7);
        webview8 = findViewById(R.id.webview8);
        webview9 = findViewById(R.id.webview9);
        webview10 = findViewById(R.id.webview10);
        webview11 = findViewById(R.id.webview11);
        webview12 = findViewById(R.id.webview12);
        webview13 = findViewById(R.id.webview13);
        webview14 = findViewById(R.id.webview14);
        webview15 = findViewById(R.id.webview15);
        webview16 = findViewById(R.id.webview16);
        webview17 = findViewById(R.id.webview17);
        webview18 = findViewById(R.id.webview18);
        webview19 = findViewById(R.id.webview19);
        webview20 = findViewById(R.id.webview20);
        webview21 = findViewById(R.id.webview21);
        webview22 = findViewById(R.id.webview22);
        webview23 = findViewById(R.id.webview23);
        webview24 = findViewById(R.id.webview24);
        webview25 = findViewById(R.id.webview25);
        webview26 = findViewById(R.id.webview26);
        webview27 = findViewById(R.id.webview27);
        webview28 = findViewById(R.id.webview28);
        webview29 = findViewById(R.id.webview29);
        webview30 = findViewById(R.id.webview30);
        webview31 = findViewById(R.id.webview31);
        webview32 = findViewById(R.id.webview32);
        webview33 = findViewById(R.id.webview33);
        webview34 = findViewById(R.id.webview34);
        webview35 = findViewById(R.id.webview35);
        webview36 = findViewById(R.id.webview36);
        webview37 = findViewById(R.id.webview37);
        webview38 = findViewById(R.id.webview38);
        webview39 = findViewById(R.id.webview39);
        webview40 = findViewById(R.id.webview40);
        webview41 = findViewById(R.id.webview41);
        webview42 = findViewById(R.id.webview42);
        webview43 = findViewById(R.id.webview43);
        webview44 = findViewById(R.id.webview44);
        webview45 = findViewById(R.id.webview45);
        webview46 = findViewById(R.id.webview46);
        webview47 = findViewById(R.id.webview47);
        webview48 = findViewById(R.id.webview48);
        webview49 = findViewById(R.id.webview49);
        webview50 = findViewById(R.id.webview50);
        webview51 = findViewById(R.id.webview51);
        webview52 = findViewById(R.id.webview52);
        webview53 = findViewById(R.id.webview53);
        webview54 = findViewById(R.id.webview54);
        webview55 = findViewById(R.id.webview55);
        webview56 = findViewById(R.id.webview56);
        webview57 = findViewById(R.id.webview57);
        webview58 = findViewById(R.id.webview58);
        webview59 = findViewById(R.id.webview59);
        webview60 = findViewById(R.id.webview60);
        webview61 = findViewById(R.id.webview61);
        webview62 = findViewById(R.id.webview62);
        webview63 = findViewById(R.id.webview63);
        webview64 = findViewById(R.id.webview64);
        webview65 = findViewById(R.id.webview65);
        webview66 = findViewById(R.id.webview66);
        webview67 = findViewById(R.id.webview67);
        webview68 = findViewById(R.id.webview68);
        webview69 = findViewById(R.id.webview69);
        webview70 = findViewById(R.id.webview70);
        webview71 = findViewById(R.id.webview71);
        webview72 = findViewById(R.id.webview72);
        webview73 = findViewById(R.id.webview73);
        webview74 = findViewById(R.id.webview74);
        webview75 = findViewById(R.id.webview75);
        webview76 = findViewById(R.id.webview76);
        webview77 = findViewById(R.id.webview77);
        webview78 = findViewById(R.id.webview78);
        webview79 = findViewById(R.id.webview79);
        webview80 = findViewById(R.id.webview80);
        webview81 = findViewById(R.id.webview81);
        webview82 = findViewById(R.id.webview82);
        webview83 = findViewById(R.id.webview83);
        webview84 = findViewById(R.id.webview84);
        webview85 = findViewById(R.id.webview85);
        webview86 = findViewById(R.id.webview86);
        webview87 = findViewById(R.id.webview87);
        webview88 = findViewById(R.id.webview88);
        webview89 = findViewById(R.id.webview89);
        webview90 = findViewById(R.id.webview90);
        webview91 = findViewById(R.id.webview91);
        webview92 = findViewById(R.id.webview92);
        webview93 = findViewById(R.id.webview93);
        webview94 = findViewById(R.id.webview94);
        webview95 = findViewById(R.id.webview95);
        webview96 = findViewById(R.id.webview96);
        webview97 = findViewById(R.id.webview97);
        webview98 = findViewById(R.id.webview98);
        webview99 = findViewById(R.id.webview99);
        webview100 = findViewById(R.id.webview100);
        webview101 = findViewById(R.id.webview101);
        webview102 = findViewById(R.id.webview102);
        webview103 = findViewById(R.id.webview103);
        webview104 = findViewById(R.id.webview104);
        webview105 = findViewById(R.id.webview105);
        webview106 = findViewById(R.id.webview106);
        webview107 = findViewById(R.id.webview107);
        webview108 = findViewById(R.id.webview108);
        webview109 = findViewById(R.id.webview109);
        webview110 = findViewById(R.id.webview110);
        webview111 = findViewById(R.id.webview111);
        webview112 = findViewById(R.id.webview112);
        webview113 = findViewById(R.id.webview113);
        webview114 = findViewById(R.id.webview114);
        webview115 = findViewById(R.id.webview115);
        webview116 = findViewById(R.id.webview116);
        webview117 = findViewById(R.id.webview117);
        webview118 = findViewById(R.id.webview118);
        webview119 = findViewById(R.id.webview119);
        webview120 = findViewById(R.id.webview120);
        webview121 = findViewById(R.id.webview121);
        webview122 = findViewById(R.id.webview122);
        webview123 = findViewById(R.id.webview123);
        webview124 = findViewById(R.id.webview124);
        webview125 = findViewById(R.id.webview125);
        webview126 = findViewById(R.id.webview126);
        webview127 = findViewById(R.id.webview127);
        webview128 = findViewById(R.id.webview128);
        webview129 = findViewById(R.id.webview129);
        webview130 = findViewById(R.id.webview130);
        webview131 = findViewById(R.id.webview131);
        webview132 = findViewById(R.id.webview132);
        webview133 = findViewById(R.id.webview133);
        webview134 = findViewById(R.id.webview134);
        webview135 = findViewById(R.id.webview135);
        webview136 = findViewById(R.id.webview136);
        webview137 = findViewById(R.id.webview137);
        webview138 = findViewById(R.id.webview138);
        webview139 = findViewById(R.id.webview139);
        webview140 = findViewById(R.id.webview140);
        webview141 = findViewById(R.id.webview141);
        webview142 = findViewById(R.id.webview142);
        webview143 = findViewById(R.id.webview143);
        webview144 = findViewById(R.id.webview144);
        webview145 = findViewById(R.id.webview145);
        webview146 = findViewById(R.id.webview146);
        webview147 = findViewById(R.id.webview147);
        webview148 = findViewById(R.id.webview148);
        webview149 = findViewById(R.id.webview149);
        webview150 = findViewById(R.id.webview150);
        webview151 = findViewById(R.id.webview151);
        webview152 = findViewById(R.id.webview152);
        webview153 = findViewById(R.id.webview153);
        webview154 = findViewById(R.id.webview154);
        webview155 = findViewById(R.id.webview155);
        webview156 = findViewById(R.id.webview156);
        webview157 = findViewById(R.id.webview157);
        webview158 = findViewById(R.id.webview158);
        webview159 = findViewById(R.id.webview159);
        webview160 = findViewById(R.id.webview160);
        webview161 = findViewById(R.id.webview161);
        webview162 = findViewById(R.id.webview162);
        webview163 = findViewById(R.id.webview163);
        webview164 = findViewById(R.id.webview164);
        webview165 = findViewById(R.id.webview165);
        webview166 = findViewById(R.id.webview166);
        webview167 = findViewById(R.id.webview167);
        webview168 = findViewById(R.id.webview168);
        webview169 = findViewById(R.id.webview169);
        webview170 = findViewById(R.id.webview170);
        webview171 = findViewById(R.id.webview171);
        webview172 = findViewById(R.id.webview172);
        webview173 = findViewById(R.id.webview173);
        webview174 = findViewById(R.id.webview174);
        webview175 = findViewById(R.id.webview175);
        webview176 = findViewById(R.id.webview176);
        webview177 = findViewById(R.id.webview177);
        webview178 = findViewById(R.id.webview178);
        webview179 = findViewById(R.id.webview179);
        webview180 = findViewById(R.id.webview180);
        webview181 = findViewById(R.id.webview181);
        webview182 = findViewById(R.id.webview182);
        webview183 = findViewById(R.id.webview183);
        webview184 = findViewById(R.id.webview184);
        webview185 = findViewById(R.id.webview185);
        webview186 = findViewById(R.id.webview186);
        webview187 = findViewById(R.id.webview187);
        webview188 = findViewById(R.id.webview188);
        webview189 = findViewById(R.id.webview189);
        webview190 = findViewById(R.id.webview190);
        webview191 = findViewById(R.id.webview191);
        webview192 = findViewById(R.id.webview192);
        webview193 = findViewById(R.id.webview193);
        webview194 = findViewById(R.id.webview194);
        webview195 = findViewById(R.id.webview195);
        webview196 = findViewById(R.id.webview196);
        webview197 = findViewById(R.id.webview197);
        webview198 = findViewById(R.id.webview198);
        webview199 = findViewById(R.id.webview199);
        webview200 = findViewById(R.id.webview200);
        webview201 = findViewById(R.id.webview201);
        webview202 = findViewById(R.id.webview202);
        webview203 = findViewById(R.id.webview203);
        webview204 = findViewById(R.id.webview204);
        webview205 = findViewById(R.id.webview205);
        webview206 = findViewById(R.id.webview206);
        webview207 = findViewById(R.id.webview207);
        webview208 = findViewById(R.id.webview208);
        webview209 = findViewById(R.id.webview209);
        webview210 = findViewById(R.id.webview210);
        webview211 = findViewById(R.id.webview211);
        webview212 = findViewById(R.id.webview212);
        webview213 = findViewById(R.id.webview213);
        webview214 = findViewById(R.id.webview214);
        webview215 = findViewById(R.id.webview215);
        webview216 = findViewById(R.id.webview216);
        webview217 = findViewById(R.id.webview217);
        webview218 = findViewById(R.id.webview218);
        webview219 = findViewById(R.id.webview219);
        webview220 = findViewById(R.id.webview220);
        webview221 = findViewById(R.id.webview221);
        webview222 = findViewById(R.id.webview222);
        webview223 = findViewById(R.id.webview223);
        webview224 = findViewById(R.id.webview224);
        webview225 = findViewById(R.id.webview225);
        webview226 = findViewById(R.id.webview226);
        webview227 = findViewById(R.id.webview227);
        webview228 = findViewById(R.id.webview228);
        webview229 = findViewById(R.id.webview229);
        webview230 = findViewById(R.id.webview230);
        webview231 = findViewById(R.id.webview231);
        webview232 = findViewById(R.id.webview232);
        webview233 = findViewById(R.id.webview233);
        webview234 = findViewById(R.id.webview234);
        webview235 = findViewById(R.id.webview235);
        webview236 = findViewById(R.id.webview236);
        webview237 = findViewById(R.id.webview237);
        webview238 = findViewById(R.id.webview238);
        webview239 = findViewById(R.id.webview239);
        webview240 = findViewById(R.id.webview240);
        webview241 = findViewById(R.id.webview241);
        webview242 = findViewById(R.id.webview242);
        webview243 = findViewById(R.id.webview243);
        webview244 = findViewById(R.id.webview244);
        webview245 = findViewById(R.id.webview245);
        webview246 = findViewById(R.id.webview246);
        webview247 = findViewById(R.id.webview247);
        webview248 = findViewById(R.id.webview248);
        webview249 = findViewById(R.id.webview249);
        webview250 = findViewById(R.id.webview250);
        webview251 = findViewById(R.id.webview251);
        webview252 = findViewById(R.id.webview252);
        webview253 = findViewById(R.id.webview253);
        webview254 = findViewById(R.id.webview254);
        webview255 = findViewById(R.id.webview255);
        webview256 = findViewById(R.id.webview256);
        webview257 = findViewById(R.id.webview257);
        webview258 = findViewById(R.id.webview258);
        webview259 = findViewById(R.id.webview259);
        webview260 = findViewById(R.id.webview260);
        webview261 = findViewById(R.id.webview261);
        webview262 = findViewById(R.id.webview262);
        webview263 = findViewById(R.id.webview263);
        webview264 = findViewById(R.id.webview264);
        webview265 = findViewById(R.id.webview265);
        webview266 = findViewById(R.id.webview266);
        webview267 = findViewById(R.id.webview267);
        webview268 = findViewById(R.id.webview268);
        webview269 = findViewById(R.id.webview269);
        webview270 = findViewById(R.id.webview270);
        webview271 = findViewById(R.id.webview271);
        webview272 = findViewById(R.id.webview272);
        webview273 = findViewById(R.id.webview273);
        webview274 = findViewById(R.id.webview274);
        webview275 = findViewById(R.id.webview275);
        webview276 = findViewById(R.id.webview276);
        webview277 = findViewById(R.id.webview277);
        webview278 = findViewById(R.id.webview278);
        webview279 = findViewById(R.id.webview279);
        webview280 = findViewById(R.id.webview280);
        webview281 = findViewById(R.id.webview281);
        webview282 = findViewById(R.id.webview282);
        webview283 = findViewById(R.id.webview283);
        webview284 = findViewById(R.id.webview284);
        webview285 = findViewById(R.id.webview285);
        webview286 = findViewById(R.id.webview286);
        webview287 = findViewById(R.id.webview287);
        webview288 = findViewById(R.id.webview288);
        webview289 = findViewById(R.id.webview289);
        webview290 = findViewById(R.id.webview290);
        webview291 = findViewById(R.id.webview291);
        webview292 = findViewById(R.id.webview292);
        webview293 = findViewById(R.id.webview293);
        webview294 = findViewById(R.id.webview294);
        webview295 = findViewById(R.id.webview295);
        webview296 = findViewById(R.id.webview296);
        webview297 = findViewById(R.id.webview297);
        webview298 = findViewById(R.id.webview298);
        webview299 = findViewById(R.id.webview299);
        webview300 = findViewById(R.id.webview300);
        webview301 = findViewById(R.id.webview301);
        webview302 = findViewById(R.id.webview302);
        webview303 = findViewById(R.id.webview303);
        webview304 = findViewById(R.id.webview304);
        webview305 = findViewById(R.id.webview305);
        webview306 = findViewById(R.id.webview306);
        webview307 = findViewById(R.id.webview307);
        webview308 = findViewById(R.id.webview308);
        webview309 = findViewById(R.id.webview309);
        webview310 = findViewById(R.id.webview310);
        webview311 = findViewById(R.id.webview311);
        webview312 = findViewById(R.id.webview312);
        webview313 = findViewById(R.id.webview313);
        webview314 = findViewById(R.id.webview314);
        webview315 = findViewById(R.id.webview315);
        webview316 = findViewById(R.id.webview316);
        webview317 = findViewById(R.id.webview317);
        webview318 = findViewById(R.id.webview318);
        webview319 = findViewById(R.id.webview319);
        webview320 = findViewById(R.id.webview320);
        webview321 = findViewById(R.id.webview321);
        webview322 = findViewById(R.id.webview322);
        webview323 = findViewById(R.id.webview323);
        webview324 = findViewById(R.id.webview324);
        webview325 = findViewById(R.id.webview325);
        webview326 = findViewById(R.id.webview326);
        webview327 = findViewById(R.id.webview327);
        webview328 = findViewById(R.id.webview328);
        webview329 = findViewById(R.id.webview329);
        webview330 = findViewById(R.id.webview330);
        webview331 = findViewById(R.id.webview331);
        webview332 = findViewById(R.id.webview332);
        webview333 = findViewById(R.id.webview333);
        webview334 = findViewById(R.id.webview334);
        webview335 = findViewById(R.id.webview335);
        webview336 = findViewById(R.id.webview336);
        webview337 = findViewById(R.id.webview337);
        webview338 = findViewById(R.id.webview338);
        webview339 = findViewById(R.id.webview339);
        webview340 = findViewById(R.id.webview340);
        webview341 = findViewById(R.id.webview341);
        webview342 = findViewById(R.id.webview342);
        webview343 = findViewById(R.id.webview343);
        webview344 = findViewById(R.id.webview344);
        webview345 = findViewById(R.id.webview345);
        webview346 = findViewById(R.id.webview346);
        webview347 = findViewById(R.id.webview347);
        webview348 = findViewById(R.id.webview348);
        webview349 = findViewById(R.id.webview349);
        webview350 = findViewById(R.id.webview350);
        webview351 = findViewById(R.id.webview351);
        webview352 = findViewById(R.id.webview352);
        webview353 = findViewById(R.id.webview353);
        webview354 = findViewById(R.id.webview354);
        webview355 = findViewById(R.id.webview355);
        webview356 = findViewById(R.id.webview356);
        webview357 = findViewById(R.id.webview357);
        webview358 = findViewById(R.id.webview358);
        webview359 = findViewById(R.id.webview359);
        webview360 = findViewById(R.id.webview360);
        webview361 = findViewById(R.id.webview361);
        webview362 = findViewById(R.id.webview362);
        webview363 = findViewById(R.id.webview363);
        webview364 = findViewById(R.id.webview364);
        webview365 = findViewById(R.id.webview365);
        webview366 = findViewById(R.id.webview366);
        webview367 = findViewById(R.id.webview367);
        webview368 = findViewById(R.id.webview368);
        webview369 = findViewById(R.id.webview369);
        webview370 = findViewById(R.id.webview370);
        webview371 = findViewById(R.id.webview371);
        webview372 = findViewById(R.id.webview372);
        webview373 = findViewById(R.id.webview373);
        webview374 = findViewById(R.id.webview374);
        webview375 = findViewById(R.id.webview375);
        webview376 = findViewById(R.id.webview376);
        webview377 = findViewById(R.id.webview377);
        webview378 = findViewById(R.id.webview378);
        webview379 = findViewById(R.id.webview379);
        webview380 = findViewById(R.id.webview380);
        webview381 = findViewById(R.id.webview381);
        webview382 = findViewById(R.id.webview382);
        webview383 = findViewById(R.id.webview383);
        webview384 = findViewById(R.id.webview384);
        webview385 = findViewById(R.id.webview385);
        webview386 = findViewById(R.id.webview386);
        webview387 = findViewById(R.id.webview387);
        webview388 = findViewById(R.id.webview388);
        webview389 = findViewById(R.id.webview389);
        webview390 = findViewById(R.id.webview390);
        webview391 = findViewById(R.id.webview391);
        webview392 = findViewById(R.id.webview392);
        webview393 = findViewById(R.id.webview393);
        webview394 = findViewById(R.id.webview394);
        webview395 = findViewById(R.id.webview395);
        webview396 = findViewById(R.id.webview396);
        webview397 = findViewById(R.id.webview397);
        webview398 = findViewById(R.id.webview398);
        webview399 = findViewById(R.id.webview399);
        webview400 = findViewById(R.id.webview400);
        webview401 = findViewById(R.id.webview401);
        webview402 = findViewById(R.id.webview402);
        webview403 = findViewById(R.id.webview403);
        webview404 = findViewById(R.id.webview404);
        webview405 = findViewById(R.id.webview405);
        webview406 = findViewById(R.id.webview406);
        webview407 = findViewById(R.id.webview407);
        webview408 = findViewById(R.id.webview408);
        webview409 = findViewById(R.id.webview409);
        webview410 = findViewById(R.id.webview410);
        webview411 = findViewById(R.id.webview411);
        webview412 = findViewById(R.id.webview412);
        webview413 = findViewById(R.id.webview413);
        webview414 = findViewById(R.id.webview414);
        webview415 = findViewById(R.id.webview415);
        webview416 = findViewById(R.id.webview416);
        webview417 = findViewById(R.id.webview417);
        webview418 = findViewById(R.id.webview418);
        webview419 = findViewById(R.id.webview419);
        webview420 = findViewById(R.id.webview420);
        webview421 = findViewById(R.id.webview421);
        webview422 = findViewById(R.id.webview422);
        webview423 = findViewById(R.id.webview423);
        webview424 = findViewById(R.id.webview424);
        webview425 = findViewById(R.id.webview425);
        webview426 = findViewById(R.id.webview426);
        webview427 = findViewById(R.id.webview427);
        webview428 = findViewById(R.id.webview428);
        webview429 = findViewById(R.id.webview429);
        webview430 = findViewById(R.id.webview430);
        webview431 = findViewById(R.id.webview431);
        webview432 = findViewById(R.id.webview432);
        webview433 = findViewById(R.id.webview433);
        webview434 = findViewById(R.id.webview434);
        webview435 = findViewById(R.id.webview435);
        webview436 = findViewById(R.id.webview436);
        webview437 = findViewById(R.id.webview437);
        webview438 = findViewById(R.id.webview438);
        webview439 = findViewById(R.id.webview439);
        webview440 = findViewById(R.id.webview440);
        webview441 = findViewById(R.id.webview441);
        webview442 = findViewById(R.id.webview442);
        webview443 = findViewById(R.id.webview443);
        webview444 = findViewById(R.id.webview444);
        webview445 = findViewById(R.id.webview445);
        webview446 = findViewById(R.id.webview446);
        webview447 = findViewById(R.id.webview447);
        webview448 = findViewById(R.id.webview448);
        webview449 = findViewById(R.id.webview449);
        webview450 = findViewById(R.id.webview450);
        webview451 = findViewById(R.id.webview451);
        webview452 = findViewById(R.id.webview452);
        webview453 = findViewById(R.id.webview453);
        webview454 = findViewById(R.id.webview454);
        webview455 = findViewById(R.id.webview455);
        webview456 = findViewById(R.id.webview456);
        webview457 = findViewById(R.id.webview457);
        webview458 = findViewById(R.id.webview458);
        webview459 = findViewById(R.id.webview459);
        webview460 = findViewById(R.id.webview460);
        webview461 = findViewById(R.id.webview461);
        webview462 = findViewById(R.id.webview462);
        webview463 = findViewById(R.id.webview463);
        webview464 = findViewById(R.id.webview464);
        webview465 = findViewById(R.id.webview465);
        webview466 = findViewById(R.id.webview466);
        webview467 = findViewById(R.id.webview467);
        webview468 = findViewById(R.id.webview468);
        webview469 = findViewById(R.id.webview469);
        webview470 = findViewById(R.id.webview470);
        webview471 = findViewById(R.id.webview471);
        webview472 = findViewById(R.id.webview472);
        webview473 = findViewById(R.id.webview473);
        webview474 = findViewById(R.id.webview474);
        webview475 = findViewById(R.id.webview475);
        webview476 = findViewById(R.id.webview476);
        webview477 = findViewById(R.id.webview477);
        webview478 = findViewById(R.id.webview478);
        webview479 = findViewById(R.id.webview479);
        webview480 = findViewById(R.id.webview480);
        webview481 = findViewById(R.id.webview481);
        webview482 = findViewById(R.id.webview482);
        webview483 = findViewById(R.id.webview483);
        webview484 = findViewById(R.id.webview484);
        webview485 = findViewById(R.id.webview485);
        webview486 = findViewById(R.id.webview486);
        webview487 = findViewById(R.id.webview487);
        webview488 = findViewById(R.id.webview488);
        webview489 = findViewById(R.id.webview489);
        webview490 = findViewById(R.id.webview490);
        webview491 = findViewById(R.id.webview491);
        webview492 = findViewById(R.id.webview492);
        webview493 = findViewById(R.id.webview493);
        webview494 = findViewById(R.id.webview494);
        webview495 = findViewById(R.id.webview495);
        webview496 = findViewById(R.id.webview496);
        webview497 = findViewById(R.id.webview497);
        webview498 = findViewById(R.id.webview498);
        webview499 = findViewById(R.id.webview499);
        webview500 = findViewById(R.id.webview500);

        setupWebView(webview1);
        setupWebView(webview2);
        setupWebView(webview3);
        setupWebView(webview4);
        setupWebView(webview5);
        setupWebView(webview6);
        setupWebView(webview7);
        setupWebView(webview8);
        setupWebView(webview9);
        setupWebView(webview10);
        setupWebView(webview11);
        setupWebView(webview12);
        setupWebView(webview13);
        setupWebView(webview14);
        setupWebView(webview15);
        setupWebView(webview16);
        setupWebView(webview17);
        setupWebView(webview18);
        setupWebView(webview19);
        setupWebView(webview20);
        setupWebView(webview21);
        setupWebView(webview22);
        setupWebView(webview23);
        setupWebView(webview24);
        setupWebView(webview25);
        setupWebView(webview26);
        setupWebView(webview27);
        setupWebView(webview28);
        setupWebView(webview29);
        setupWebView(webview30);
        setupWebView(webview31);
        setupWebView(webview32);
        setupWebView(webview33);
        setupWebView(webview34);
        setupWebView(webview35);
        setupWebView(webview36);
        setupWebView(webview37);
        setupWebView(webview38);
        setupWebView(webview39);
        setupWebView(webview40);
        setupWebView(webview41);
        setupWebView(webview42);
        setupWebView(webview43);
        setupWebView(webview44);
        setupWebView(webview45);
        setupWebView(webview46);
        setupWebView(webview47);
        setupWebView(webview48);
        setupWebView(webview49);
        setupWebView(webview50);
        setupWebView(webview51);
        setupWebView(webview52);
        setupWebView(webview53);
        setupWebView(webview54);
        setupWebView(webview55);
        setupWebView(webview56);
        setupWebView(webview57);
        setupWebView(webview58);
        setupWebView(webview59);
        setupWebView(webview60);
        setupWebView(webview61);
        setupWebView(webview62);
        setupWebView(webview63);
        setupWebView(webview64);
        setupWebView(webview65);
        setupWebView(webview66);
        setupWebView(webview67);
        setupWebView(webview68);
        setupWebView(webview69);
        setupWebView(webview70);
        setupWebView(webview71);
        setupWebView(webview72);
        setupWebView(webview73);
        setupWebView(webview74);
        setupWebView(webview75);
        setupWebView(webview76);
        setupWebView(webview77);
        setupWebView(webview78);
        setupWebView(webview79);
        setupWebView(webview80);
        setupWebView(webview81);
        setupWebView(webview82);
        setupWebView(webview83);
        setupWebView(webview84);
        setupWebView(webview85);
        setupWebView(webview86);
        setupWebView(webview87);
        setupWebView(webview88);
        setupWebView(webview89);
        setupWebView(webview90);
        setupWebView(webview91);
        setupWebView(webview92);
        setupWebView(webview93);
        setupWebView(webview94);
        setupWebView(webview95);
        setupWebView(webview96);
        setupWebView(webview97);
        setupWebView(webview98);
        setupWebView(webview99);
        setupWebView(webview100);
        setupWebView(webview101);
        setupWebView(webview102);
        setupWebView(webview103);
        setupWebView(webview104);
        setupWebView(webview105);
        setupWebView(webview106);
        setupWebView(webview107);
        setupWebView(webview108);
        setupWebView(webview109);
        setupWebView(webview110);
        setupWebView(webview111);
        setupWebView(webview112);
        setupWebView(webview113);
        setupWebView(webview114);
        setupWebView(webview115);
        setupWebView(webview116);
        setupWebView(webview117);
        setupWebView(webview118);
        setupWebView(webview119);
        setupWebView(webview120);
        setupWebView(webview121);
        setupWebView(webview122);
        setupWebView(webview123);
        setupWebView(webview124);
        setupWebView(webview125);
        setupWebView(webview126);
        setupWebView(webview127);
        setupWebView(webview128);
        setupWebView(webview129);
        setupWebView(webview130);
        setupWebView(webview131);
        setupWebView(webview132);
        setupWebView(webview133);
        setupWebView(webview134);
        setupWebView(webview135);
        setupWebView(webview136);
        setupWebView(webview137);
        setupWebView(webview138);
        setupWebView(webview139);
        setupWebView(webview140);
        setupWebView(webview141);
        setupWebView(webview142);
        setupWebView(webview143);
        setupWebView(webview144);
        setupWebView(webview145);
        setupWebView(webview146);
        setupWebView(webview147);
        setupWebView(webview148);
        setupWebView(webview149);
        setupWebView(webview150);
        setupWebView(webview151);
        setupWebView(webview152);
        setupWebView(webview153);
        setupWebView(webview154);
        setupWebView(webview155);
        setupWebView(webview156);
        setupWebView(webview157);
        setupWebView(webview158);
        setupWebView(webview159);
        setupWebView(webview160);
        setupWebView(webview161);
        setupWebView(webview162);
        setupWebView(webview163);
        setupWebView(webview164);
        setupWebView(webview165);
        setupWebView(webview166);
        setupWebView(webview167);
        setupWebView(webview168);
        setupWebView(webview169);
        setupWebView(webview170);
        setupWebView(webview171);
        setupWebView(webview172);
        setupWebView(webview173);
        setupWebView(webview174);
        setupWebView(webview175);
        setupWebView(webview176);
        setupWebView(webview177);
        setupWebView(webview178);
        setupWebView(webview179);
        setupWebView(webview180);
        setupWebView(webview181);
        setupWebView(webview182);
        setupWebView(webview183);
        setupWebView(webview184);
        setupWebView(webview185);
        setupWebView(webview186);
        setupWebView(webview187);
        setupWebView(webview188);
        setupWebView(webview189);
        setupWebView(webview190);
        setupWebView(webview191);
        setupWebView(webview192);
        setupWebView(webview193);
        setupWebView(webview194);
        setupWebView(webview195);
        setupWebView(webview196);
        setupWebView(webview197);
        setupWebView(webview198);
        setupWebView(webview199);
        setupWebView(webview200);
        setupWebView(webview201);
        setupWebView(webview202);
        setupWebView(webview203);
        setupWebView(webview204);
        setupWebView(webview205);
        setupWebView(webview206);
        setupWebView(webview207);
        setupWebView(webview208);
        setupWebView(webview209);
        setupWebView(webview210);
        setupWebView(webview211);
        setupWebView(webview212);
        setupWebView(webview213);
        setupWebView(webview214);
        setupWebView(webview215);
        setupWebView(webview216);
        setupWebView(webview217);
        setupWebView(webview218);
        setupWebView(webview219);
        setupWebView(webview220);
        setupWebView(webview221);
        setupWebView(webview222);
        setupWebView(webview223);
        setupWebView(webview224);
        setupWebView(webview225);
        setupWebView(webview226);
        setupWebView(webview227);
        setupWebView(webview228);
        setupWebView(webview229);
        setupWebView(webview230);
        setupWebView(webview231);
        setupWebView(webview232);
        setupWebView(webview233);
        setupWebView(webview234);
        setupWebView(webview235);
        setupWebView(webview236);
        setupWebView(webview237);
        setupWebView(webview238);
        setupWebView(webview239);
        setupWebView(webview240);
        setupWebView(webview241);
        setupWebView(webview242);
        setupWebView(webview243);
        setupWebView(webview244);
        setupWebView(webview245);
        setupWebView(webview246);
        setupWebView(webview247);
        setupWebView(webview248);
        setupWebView(webview249);
        setupWebView(webview250);
        setupWebView(webview251);
        setupWebView(webview252);
        setupWebView(webview253);
        setupWebView(webview254);
        setupWebView(webview255);
        setupWebView(webview256);
        setupWebView(webview257);
        setupWebView(webview258);
        setupWebView(webview259);
        setupWebView(webview260);
        setupWebView(webview261);
        setupWebView(webview262);
        setupWebView(webview263);
        setupWebView(webview264);
        setupWebView(webview265);
        setupWebView(webview266);
        setupWebView(webview267);
        setupWebView(webview268);
        setupWebView(webview269);
        setupWebView(webview270);
        setupWebView(webview271);
        setupWebView(webview272);
        setupWebView(webview273);
        setupWebView(webview274);
        setupWebView(webview275);
        setupWebView(webview276);
        setupWebView(webview277);
        setupWebView(webview278);
        setupWebView(webview279);
        setupWebView(webview280);
        setupWebView(webview281);
        setupWebView(webview282);
        setupWebView(webview283);
        setupWebView(webview284);
        setupWebView(webview285);
        setupWebView(webview286);
        setupWebView(webview287);
        setupWebView(webview288);
        setupWebView(webview289);
        setupWebView(webview290);
        setupWebView(webview291);
        setupWebView(webview292);
        setupWebView(webview293);
        setupWebView(webview294);
        setupWebView(webview295);
        setupWebView(webview296);
        setupWebView(webview297);
        setupWebView(webview298);
        setupWebView(webview299);
        setupWebView(webview300);
        setupWebView(webview301);
        setupWebView(webview302);
        setupWebView(webview303);
        setupWebView(webview304);
        setupWebView(webview305);
        setupWebView(webview306);
        setupWebView(webview307);
        setupWebView(webview308);
        setupWebView(webview309);
        setupWebView(webview310);
        setupWebView(webview311);
        setupWebView(webview312);
        setupWebView(webview313);
        setupWebView(webview314);
        setupWebView(webview315);
        setupWebView(webview316);
        setupWebView(webview317);
        setupWebView(webview318);
        setupWebView(webview319);
        setupWebView(webview320);
        setupWebView(webview321);
        setupWebView(webview322);
        setupWebView(webview323);
        setupWebView(webview324);
        setupWebView(webview325);
        setupWebView(webview326);
        setupWebView(webview327);
        setupWebView(webview328);
        setupWebView(webview329);
        setupWebView(webview330);
        setupWebView(webview331);
        setupWebView(webview332);
        setupWebView(webview333);
        setupWebView(webview334);
        setupWebView(webview335);
        setupWebView(webview336);
        setupWebView(webview337);
        setupWebView(webview338);
        setupWebView(webview339);
        setupWebView(webview340);
        setupWebView(webview341);
        setupWebView(webview342);
        setupWebView(webview343);
        setupWebView(webview344);
        setupWebView(webview345);
        setupWebView(webview346);
        setupWebView(webview347);
        setupWebView(webview348);
        setupWebView(webview349);
        setupWebView(webview350);
        setupWebView(webview351);
        setupWebView(webview352);
        setupWebView(webview353);
        setupWebView(webview354);
        setupWebView(webview355);
        setupWebView(webview356);
        setupWebView(webview357);
        setupWebView(webview358);
        setupWebView(webview359);
        setupWebView(webview360);
        setupWebView(webview361);
        setupWebView(webview362);
        setupWebView(webview363);
        setupWebView(webview364);
        setupWebView(webview365);
        setupWebView(webview366);
        setupWebView(webview367);
        setupWebView(webview368);
        setupWebView(webview369);
        setupWebView(webview370);
        setupWebView(webview371);
        setupWebView(webview372);
        setupWebView(webview373);
        setupWebView(webview374);
        setupWebView(webview375);
        setupWebView(webview376);
        setupWebView(webview377);
        setupWebView(webview378);
        setupWebView(webview379);
        setupWebView(webview380);
        setupWebView(webview381);
        setupWebView(webview382);
        setupWebView(webview383);
        setupWebView(webview384);
        setupWebView(webview385);
        setupWebView(webview386);
        setupWebView(webview387);
        setupWebView(webview388);
        setupWebView(webview389);
        setupWebView(webview390);
        setupWebView(webview391);
        setupWebView(webview392);
        setupWebView(webview393);
        setupWebView(webview394);
        setupWebView(webview395);
        setupWebView(webview396);
        setupWebView(webview397);
        setupWebView(webview398);
        setupWebView(webview399);
        setupWebView(webview400);
        setupWebView(webview401);
        setupWebView(webview402);
        setupWebView(webview403);
        setupWebView(webview404);
        setupWebView(webview405);
        setupWebView(webview406);
        setupWebView(webview407);
        setupWebView(webview408);
        setupWebView(webview409);
        setupWebView(webview410);
        setupWebView(webview411);
        setupWebView(webview412);
        setupWebView(webview413);
        setupWebView(webview414);
        setupWebView(webview415);
        setupWebView(webview416);
        setupWebView(webview417);
        setupWebView(webview418);
        setupWebView(webview419);
        setupWebView(webview420);
        setupWebView(webview421);
        setupWebView(webview422);
        setupWebView(webview423);
        setupWebView(webview424);
        setupWebView(webview425);
        setupWebView(webview426);
        setupWebView(webview427);
        setupWebView(webview428);
        setupWebView(webview429);
        setupWebView(webview430);
        setupWebView(webview431);
        setupWebView(webview432);
        setupWebView(webview433);
        setupWebView(webview434);
        setupWebView(webview435);
        setupWebView(webview436);
        setupWebView(webview437);
        setupWebView(webview438);
        setupWebView(webview439);
        setupWebView(webview440);
        setupWebView(webview441);
        setupWebView(webview442);
        setupWebView(webview443);
        setupWebView(webview444);
        setupWebView(webview445);
        setupWebView(webview446);
        setupWebView(webview447);
        setupWebView(webview448);
        setupWebView(webview449);
        setupWebView(webview450);
        setupWebView(webview451);
        setupWebView(webview452);
        setupWebView(webview453);
        setupWebView(webview454);
        setupWebView(webview455);
        setupWebView(webview456);
        setupWebView(webview457);
        setupWebView(webview458);
        setupWebView(webview459);
        setupWebView(webview460);
        setupWebView(webview461);
        setupWebView(webview462);
        setupWebView(webview463);
        setupWebView(webview464);
        setupWebView(webview465);
        setupWebView(webview466);
        setupWebView(webview467);
        setupWebView(webview468);
        setupWebView(webview469);
        setupWebView(webview470);
        setupWebView(webview471);
        setupWebView(webview472);
        setupWebView(webview473);
        setupWebView(webview474);
        setupWebView(webview475);
        setupWebView(webview476);
        setupWebView(webview477);
        setupWebView(webview478);
        setupWebView(webview479);
        setupWebView(webview480);
        setupWebView(webview481);
        setupWebView(webview482);
        setupWebView(webview483);
        setupWebView(webview484);
        setupWebView(webview485);
        setupWebView(webview486);
        setupWebView(webview487);
        setupWebView(webview488);
        setupWebView(webview489);
        setupWebView(webview490);
        setupWebView(webview491);
        setupWebView(webview492);
        setupWebView(webview493);
        setupWebView(webview494);
        setupWebView(webview495);
        setupWebView(webview496);
        setupWebView(webview497);
        setupWebView(webview498);
        setupWebView(webview499);
        setupWebView(webview500);
    }

    private void setupWebView(WebView webView) {
        webView.getSettings().setJavaScriptEnabled(true);
        webView.getSettings().setSupportZoom(true);
        webView.setWebViewClient(new WebViewClient());
    }

    private void loadVideos() {
        link = getIntent().getStringExtra("500");
        if (link == null || link.isEmpty()) {
            Toast.makeText(this, "No URL provided", Toast.LENGTH_SHORT).show();
            return;
        }

        webview1.loadUrl(link);
        webview2.loadUrl(link);
        webview3.loadUrl(link);
        webview4.loadUrl(link);
        webview5.loadUrl(link);
        webview6.loadUrl(link);
        webview7.loadUrl(link);
        webview8.loadUrl(link);
        webview9.loadUrl(link);
        webview10.loadUrl(link);
        webview11.loadUrl(link);
        webview12.loadUrl(link);
        webview13.loadUrl(link);
        webview14.loadUrl(link);
        webview15.loadUrl(link);
        webview16.loadUrl(link);
        webview17.loadUrl(link);
        webview18.loadUrl(link);
        webview19.loadUrl(link);
        webview20.loadUrl(link);
        webview21.loadUrl(link);
        webview22.loadUrl(link);
        webview23.loadUrl(link);
        webview24.loadUrl(link);
        webview25.loadUrl(link);
        webview26.loadUrl(link);
        webview27.loadUrl(link);
        webview28.loadUrl(link);
        webview29.loadUrl(link);
        webview30.loadUrl(link);
        webview31.loadUrl(link);
        webview32.loadUrl(link);
        webview33.loadUrl(link);
        webview34.loadUrl(link);
        webview35.loadUrl(link);
        webview36.loadUrl(link);
        webview37.loadUrl(link);
        webview38.loadUrl(link);
        webview39.loadUrl(link);
        webview40.loadUrl(link);
        webview41.loadUrl(link);
        webview42.loadUrl(link);
        webview43.loadUrl(link);
        webview44.loadUrl(link);
        webview45.loadUrl(link);
        webview46.loadUrl(link);
        webview47.loadUrl(link);
        webview48.loadUrl(link);
        webview49.loadUrl(link);
        webview50.loadUrl(link);
        webview51.loadUrl(link);
        webview52.loadUrl(link);
        webview53.loadUrl(link);
        webview54.loadUrl(link);
        webview55.loadUrl(link);
        webview56.loadUrl(link);
        webview57.loadUrl(link);
        webview58.loadUrl(link);
        webview59.loadUrl(link);
        webview60.loadUrl(link);
        webview61.loadUrl(link);
        webview62.loadUrl(link);
        webview63.loadUrl(link);
        webview64.loadUrl(link);
        webview65.loadUrl(link);
        webview66.loadUrl(link);
        webview67.loadUrl(link);
        webview68.loadUrl(link);
        webview69.loadUrl(link);
        webview70.loadUrl(link);
        webview71.loadUrl(link);
        webview72.loadUrl(link);
        webview73.loadUrl(link);
        webview74.loadUrl(link);
        webview75.loadUrl(link);
        webview76.loadUrl(link);
        webview77.loadUrl(link);
        webview78.loadUrl(link);
        webview79.loadUrl(link);
        webview80.loadUrl(link);
        webview81.loadUrl(link);
        webview82.loadUrl(link);
        webview83.loadUrl(link);
        webview84.loadUrl(link);
        webview85.loadUrl(link);
        webview86.loadUrl(link);
        webview87.loadUrl(link);
        webview88.loadUrl(link);
        webview89.loadUrl(link);
        webview90.loadUrl(link);
        webview91.loadUrl(link);
        webview92.loadUrl(link);
        webview93.loadUrl(link);
        webview94.loadUrl(link);
        webview95.loadUrl(link);
        webview96.loadUrl(link);
        webview97.loadUrl(link);
        webview98.loadUrl(link);
        webview99.loadUrl(link);
        webview100.loadUrl(link);
        webview101.loadUrl(link);
        webview102.loadUrl(link);
        webview103.loadUrl(link);
        webview104.loadUrl(link);
        webview105.loadUrl(link);
        webview106.loadUrl(link);
        webview107.loadUrl(link);
        webview108.loadUrl(link);
        webview109.loadUrl(link);
        webview110.loadUrl(link);
        webview111.loadUrl(link);
        webview112.loadUrl(link);
        webview113.loadUrl(link);
        webview114.loadUrl(link);
        webview115.loadUrl(link);
        webview116.loadUrl(link);
        webview117.loadUrl(link);
        webview118.loadUrl(link);
        webview119.loadUrl(link);
        webview120.loadUrl(link);
        webview121.loadUrl(link);
        webview122.loadUrl(link);
        webview123.loadUrl(link);
        webview124.loadUrl(link);
        webview125.loadUrl(link);
        webview126.loadUrl(link);
        webview127.loadUrl(link);
        webview128.loadUrl(link);
        webview129.loadUrl(link);
        webview130.loadUrl(link);
        webview131.loadUrl(link);
        webview132.loadUrl(link);
        webview133.loadUrl(link);
        webview134.loadUrl(link);
        webview135.loadUrl(link);
        webview136.loadUrl(link);
        webview137.loadUrl(link);
        webview138.loadUrl(link);
        webview139.loadUrl(link);
        webview140.loadUrl(link);
        webview141.loadUrl(link);
        webview142.loadUrl(link);
        webview143.loadUrl(link);
        webview144.loadUrl(link);
        webview145.loadUrl(link);
        webview146.loadUrl(link);
        webview147.loadUrl(link);
        webview148.loadUrl(link);
        webview149.loadUrl(link);
        webview150.loadUrl(link);
        webview151.loadUrl(link);
        webview152.loadUrl(link);
        webview153.loadUrl(link);
        webview154.loadUrl(link);
        webview155.loadUrl(link);
        webview156.loadUrl(link);
        webview157.loadUrl(link);
        webview158.loadUrl(link);
        webview159.loadUrl(link);
        webview160.loadUrl(link);
        webview161.loadUrl(link);
        webview162.loadUrl(link);
        webview163.loadUrl(link);
        webview164.loadUrl(link);
        webview165.loadUrl(link);
        webview166.loadUrl(link);
        webview167.loadUrl(link);
        webview168.loadUrl(link);
        webview169.loadUrl(link);
        webview170.loadUrl(link);
        webview171.loadUrl(link);
        webview172.loadUrl(link);
        webview173.loadUrl(link);
        webview174.loadUrl(link);
        webview175.loadUrl(link);
        webview176.loadUrl(link);
        webview177.loadUrl(link);
        webview178.loadUrl(link);
        webview179.loadUrl(link);
        webview180.loadUrl(link);
        webview181.loadUrl(link);
        webview182.loadUrl(link);
        webview183.loadUrl(link);
        webview184.loadUrl(link);
        webview185.loadUrl(link);
        webview186.loadUrl(link);
        webview187.loadUrl(link);
        webview188.loadUrl(link);
        webview189.loadUrl(link);
        webview190.loadUrl(link);
        webview191.loadUrl(link);
        webview192.loadUrl(link);
        webview193.loadUrl(link);
        webview194.loadUrl(link);
        webview195.loadUrl(link);
        webview196.loadUrl(link);
        webview197.loadUrl(link);
        webview198.loadUrl(link);
        webview199.loadUrl(link);
        webview200.loadUrl(link);
        webview201.loadUrl(link);
        webview202.loadUrl(link);
        webview203.loadUrl(link);
        webview204.loadUrl(link);
        webview205.loadUrl(link);
        webview206.loadUrl(link);
        webview207.loadUrl(link);
        webview208.loadUrl(link);
        webview209.loadUrl(link);
        webview210.loadUrl(link);
        webview211.loadUrl(link);
        webview212.loadUrl(link);
        webview213.loadUrl(link);
        webview214.loadUrl(link);
        webview215.loadUrl(link);
        webview216.loadUrl(link);
        webview217.loadUrl(link);
        webview218.loadUrl(link);
        webview219.loadUrl(link);
        webview220.loadUrl(link);
        webview221.loadUrl(link);
        webview222.loadUrl(link);
        webview223.loadUrl(link);
        webview224.loadUrl(link);
        webview225.loadUrl(link);
        webview226.loadUrl(link);
        webview227.loadUrl(link);
        webview228.loadUrl(link);
        webview229.loadUrl(link);
        webview230.loadUrl(link);
        webview231.loadUrl(link);
        webview232.loadUrl(link);
        webview233.loadUrl(link);
        webview234.loadUrl(link);
        webview235.loadUrl(link);
        webview236.loadUrl(link);
        webview237.loadUrl(link);
        webview238.loadUrl(link);
        webview239.loadUrl(link);
        webview240.loadUrl(link);
        webview241.loadUrl(link);
        webview242.loadUrl(link);
        webview243.loadUrl(link);
        webview244.loadUrl(link);
        webview245.loadUrl(link);
        webview246.loadUrl(link);
        webview247.loadUrl(link);
        webview248.loadUrl(link);
        webview249.loadUrl(link);
        webview250.loadUrl(link);
        webview251.loadUrl(link);
        webview252.loadUrl(link);
        webview253.loadUrl(link);
        webview254.loadUrl(link);
        webview255.loadUrl(link);
        webview256.loadUrl(link);
        webview257.loadUrl(link);
        webview258.loadUrl(link);
        webview259.loadUrl(link);
        webview260.loadUrl(link);
        webview261.loadUrl(link);
        webview262.loadUrl(link);
        webview263.loadUrl(link);
        webview264.loadUrl(link);
        webview265.loadUrl(link);
        webview266.loadUrl(link);
        webview267.loadUrl(link);
        webview268.loadUrl(link);
        webview269.loadUrl(link);
        webview270.loadUrl(link);
        webview271.loadUrl(link);
        webview272.loadUrl(link);
        webview273.loadUrl(link);
        webview274.loadUrl(link);
        webview275.loadUrl(link);
        webview276.loadUrl(link);
        webview277.loadUrl(link);
        webview278.loadUrl(link);
        webview279.loadUrl(link);
        webview280.loadUrl(link);
        webview281.loadUrl(link);
        webview282.loadUrl(link);
        webview283.loadUrl(link);
        webview284.loadUrl(link);
        webview285.loadUrl(link);
        webview286.loadUrl(link);
        webview287.loadUrl(link);
        webview288.loadUrl(link);
        webview289.loadUrl(link);
        webview290.loadUrl(link);
        webview291.loadUrl(link);
        webview292.loadUrl(link);
        webview293.loadUrl(link);
        webview294.loadUrl(link);
        webview295.loadUrl(link);
        webview296.loadUrl(link);
        webview297.loadUrl(link);
        webview298.loadUrl(link);
        webview299.loadUrl(link);
        webview300.loadUrl(link);
        webview301.loadUrl(link);
        webview302.loadUrl(link);
        webview303.loadUrl(link);
        webview304.loadUrl(link);
        webview305.loadUrl(link);
        webview306.loadUrl(link);
        webview307.loadUrl(link);
        webview308.loadUrl(link);
        webview309.loadUrl(link);
        webview310.loadUrl(link);
        webview311.loadUrl(link);
        webview312.loadUrl(link);
        webview313.loadUrl(link);
        webview314.loadUrl(link);
        webview315.loadUrl(link);
        webview316.loadUrl(link);
        webview317.loadUrl(link);
        webview318.loadUrl(link);
        webview319.loadUrl(link);
        webview320.loadUrl(link);
        webview321.loadUrl(link);
        webview322.loadUrl(link);
        webview323.loadUrl(link);
        webview324.loadUrl(link);
        webview325.loadUrl(link);
        webview326.loadUrl(link);
        webview327.loadUrl(link);
        webview328.loadUrl(link);
        webview329.loadUrl(link);
        webview330.loadUrl(link);
        webview331.loadUrl(link);
        webview332.loadUrl(link);
        webview333.loadUrl(link);
        webview334.loadUrl(link);
        webview335.loadUrl(link);
        webview336.loadUrl(link);
        webview337.loadUrl(link);
        webview338.loadUrl(link);
        webview339.loadUrl(link);
        webview340.loadUrl(link);
        webview341.loadUrl(link);
        webview342.loadUrl(link);
        webview343.loadUrl(link);
        webview344.loadUrl(link);
        webview345.loadUrl(link);
        webview346.loadUrl(link);
        webview347.loadUrl(link);
        webview348.loadUrl(link);
        webview349.loadUrl(link);
        webview350.loadUrl(link);
        webview351.loadUrl(link);
        webview352.loadUrl(link);
        webview353.loadUrl(link);
        webview354.loadUrl(link);
        webview355.loadUrl(link);
        webview356.loadUrl(link);
        webview357.loadUrl(link);
        webview358.loadUrl(link);
        webview359.loadUrl(link);
        webview360.loadUrl(link);
        webview361.loadUrl(link);
        webview362.loadUrl(link);
        webview363.loadUrl(link);
        webview364.loadUrl(link);
        webview365.loadUrl(link);
        webview366.loadUrl(link);
        webview367.loadUrl(link);
        webview368.loadUrl(link);
        webview369.loadUrl(link);
        webview370.loadUrl(link);
        webview371.loadUrl(link);
        webview372.loadUrl(link);
        webview373.loadUrl(link);
        webview374.loadUrl(link);
        webview375.loadUrl(link);
        webview376.loadUrl(link);
        webview377.loadUrl(link);
        webview378.loadUrl(link);
        webview379.loadUrl(link);
        webview380.loadUrl(link);
        webview381.loadUrl(link);
        webview382.loadUrl(link);
        webview383.loadUrl(link);
        webview384.loadUrl(link);
        webview385.loadUrl(link);
        webview386.loadUrl(link);
        webview387.loadUrl(link);
        webview388.loadUrl(link);
        webview389.loadUrl(link);
        webview390.loadUrl(link);
        webview391.loadUrl(link);
        webview392.loadUrl(link);
        webview393.loadUrl(link);
        webview394.loadUrl(link);
        webview395.loadUrl(link);
        webview396.loadUrl(link);
        webview397.loadUrl(link);
        webview398.loadUrl(link);
        webview399.loadUrl(link);
        webview400.loadUrl(link);
        webview401.loadUrl(link);
        webview402.loadUrl(link);
        webview403.loadUrl(link);
        webview404.loadUrl(link);
        webview405.loadUrl(link);
        webview406.loadUrl(link);
        webview407.loadUrl(link);
        webview408.loadUrl(link);
        webview409.loadUrl(link);
        webview410.loadUrl(link);
        webview411.loadUrl(link);
        webview412.loadUrl(link);
        webview413.loadUrl(link);
        webview414.loadUrl(link);
        webview415.loadUrl(link);
        webview416.loadUrl(link);
        webview417.loadUrl(link);
        webview418.loadUrl(link);
        webview419.loadUrl(link);
        webview420.loadUrl(link);
        webview421.loadUrl(link);
        webview422.loadUrl(link);
        webview423.loadUrl(link);
        webview424.loadUrl(link);
        webview425.loadUrl(link);
        webview426.loadUrl(link);
        webview427.loadUrl(link);
        webview428.loadUrl(link);
        webview429.loadUrl(link);
        webview430.loadUrl(link);
        webview431.loadUrl(link);
        webview432.loadUrl(link);
        webview433.loadUrl(link);
        webview434.loadUrl(link);
        webview435.loadUrl(link);
        webview436.loadUrl(link);
        webview437.loadUrl(link);
        webview438.loadUrl(link);
        webview439.loadUrl(link);
        webview440.loadUrl(link);
        webview441.loadUrl(link);
        webview442.loadUrl(link);
        webview443.loadUrl(link);
        webview444.loadUrl(link);
        webview445.loadUrl(link);
        webview446.loadUrl(link);
        webview447.loadUrl(link);
        webview448.loadUrl(link);
        webview449.loadUrl(link);
        webview450.loadUrl(link);
        webview451.loadUrl(link);
        webview452.loadUrl(link);
        webview453.loadUrl(link);
        webview454.loadUrl(link);
        webview455.loadUrl(link);
        webview456.loadUrl(link);
        webview457.loadUrl(link);
        webview458.loadUrl(link);
        webview459.loadUrl(link);
        webview460.loadUrl(link);
        webview461.loadUrl(link);
        webview462.loadUrl(link);
        webview463.loadUrl(link);
        webview464.loadUrl(link);
        webview465.loadUrl(link);
        webview466.loadUrl(link);
        webview467.loadUrl(link);
        webview468.loadUrl(link);
        webview469.loadUrl(link);
        webview470.loadUrl(link);
        webview471.loadUrl(link);
        webview472.loadUrl(link);
        webview473.loadUrl(link);
        webview474.loadUrl(link);
        webview475.loadUrl(link);
        webview476.loadUrl(link);
        webview477.loadUrl(link);
        webview478.loadUrl(link);
        webview479.loadUrl(link);
        webview480.loadUrl(link);
        webview481.loadUrl(link);
        webview482.loadUrl(link);
        webview483.loadUrl(link);
        webview484.loadUrl(link);
        webview485.loadUrl(link);
        webview486.loadUrl(link);
        webview487.loadUrl(link);
        webview488.loadUrl(link);
        webview489.loadUrl(link);
        webview490.loadUrl(link);
        webview491.loadUrl(link);
        webview492.loadUrl(link);
        webview493.loadUrl(link);
        webview494.loadUrl(link);
        webview495.loadUrl(link);
        webview496.loadUrl(link);
        webview497.loadUrl(link);
        webview498.loadUrl(link);
        webview499.loadUrl(link);
        webview500.loadUrl(link);
    }

    @Override
    public void onBackPressed() {
        Intent intent = new Intent(this, HomeActivity.class);
        startActivity(intent);
        finish();
    }
}
