package com.my.youtubewatchtime.view.sa;

import android.content.Intent;
import android.os.Bundle;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;


public class Video100Activity extends AppCompatActivity {
        private WebView webview1;
    private WebView webview2;
    private WebView webview3;
    private WebView webview4;
    private WebView webview5;
    private WebView webview6;
    private WebView webview7;
    private WebView webview8;
    private WebView webview9;
    private WebView webview10;
    private WebView webview11;
    private WebView webview12;
    private WebView webview13;
    private WebView webview14;
    private WebView webview15;
    private WebView webview16;
    private WebView webview17;
    private WebView webview18;
    private WebView webview19;
    private WebView webview20;
    private WebView webview21;
    private WebView webview22;
    private WebView webview23;
    private WebView webview24;
    private WebView webview25;
    private WebView webview26;
    private WebView webview27;
    private WebView webview28;
    private WebView webview29;
    private WebView webview30;
    private WebView webview31;
    private WebView webview32;
    private WebView webview33;
    private WebView webview34;
    private WebView webview35;
    private WebView webview36;
    private WebView webview37;
    private WebView webview38;
    private WebView webview39;
    private WebView webview40;
    private WebView webview41;
    private WebView webview42;
    private WebView webview43;
    private WebView webview44;
    private WebView webview45;
    private WebView webview46;
    private WebView webview47;
    private WebView webview48;
    private WebView webview49;
    private WebView webview50;
    private WebView webview51;
    private WebView webview52;
    private WebView webview53;
    private WebView webview54;
    private WebView webview55;
    private WebView webview56;
    private WebView webview57;
    private WebView webview58;
    private WebView webview59;
    private WebView webview60;
    private WebView webview61;
    private WebView webview62;
    private WebView webview63;
    private WebView webview64;
    private WebView webview65;
    private WebView webview66;
    private WebView webview67;
    private WebView webview68;
    private WebView webview69;
    private WebView webview70;
    private WebView webview71;
    private WebView webview72;
    private WebView webview73;
    private WebView webview74;
    private WebView webview75;
    private WebView webview76;
    private WebView webview77;
    private WebView webview78;
    private WebView webview79;
    private WebView webview80;
    private WebView webview81;
    private WebView webview82;
    private WebView webview83;
    private WebView webview84;
    private WebView webview85;
    private WebView webview86;
    private WebView webview87;
    private WebView webview88;
    private WebView webview89;
    private WebView webview90;
    private WebView webview91;
    private WebView webview92;
    private WebView webview93;
    private WebView webview94;
    private WebView webview95;
    private WebView webview96;
    private WebView webview97;
    private WebView webview98;
    private WebView webview99;
    private WebView webview100;
    private String link = "";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video100);

        initializeViews();
        loadVideos();
    }

    private void initializeViews() {
                webview1 = findViewById(R.id.webview1);
        webview2 = findViewById(R.id.webview2);
        webview3 = findViewById(R.id.webview3);
        webview4 = findViewById(R.id.webview4);
        webview5 = findViewById(R.id.webview5);
        webview6 = findViewById(R.id.webview6);
        webview7 = findViewById(R.id.webview7);
        webview8 = findViewById(R.id.webview8);
        webview9 = findViewById(R.id.webview9);
        webview10 = findViewById(R.id.webview10);
        webview11 = findViewById(R.id.webview11);
        webview12 = findViewById(R.id.webview12);
        webview13 = findViewById(R.id.webview13);
        webview14 = findViewById(R.id.webview14);
        webview15 = findViewById(R.id.webview15);
        webview16 = findViewById(R.id.webview16);
        webview17 = findViewById(R.id.webview17);
        webview18 = findViewById(R.id.webview18);
        webview19 = findViewById(R.id.webview19);
        webview20 = findViewById(R.id.webview20);
        webview21 = findViewById(R.id.webview21);
        webview22 = findViewById(R.id.webview22);
        webview23 = findViewById(R.id.webview23);
        webview24 = findViewById(R.id.webview24);
        webview25 = findViewById(R.id.webview25);
        webview26 = findViewById(R.id.webview26);
        webview27 = findViewById(R.id.webview27);
        webview28 = findViewById(R.id.webview28);
        webview29 = findViewById(R.id.webview29);
        webview30 = findViewById(R.id.webview30);
        webview31 = findViewById(R.id.webview31);
        webview32 = findViewById(R.id.webview32);
        webview33 = findViewById(R.id.webview33);
        webview34 = findViewById(R.id.webview34);
        webview35 = findViewById(R.id.webview35);
        webview36 = findViewById(R.id.webview36);
        webview37 = findViewById(R.id.webview37);
        webview38 = findViewById(R.id.webview38);
        webview39 = findViewById(R.id.webview39);
        webview40 = findViewById(R.id.webview40);
        webview41 = findViewById(R.id.webview41);
        webview42 = findViewById(R.id.webview42);
        webview43 = findViewById(R.id.webview43);
        webview44 = findViewById(R.id.webview44);
        webview45 = findViewById(R.id.webview45);
        webview46 = findViewById(R.id.webview46);
        webview47 = findViewById(R.id.webview47);
        webview48 = findViewById(R.id.webview48);
        webview49 = findViewById(R.id.webview49);
        webview50 = findViewById(R.id.webview50);
        webview51 = findViewById(R.id.webview51);
        webview52 = findViewById(R.id.webview52);
        webview53 = findViewById(R.id.webview53);
        webview54 = findViewById(R.id.webview54);
        webview55 = findViewById(R.id.webview55);
        webview56 = findViewById(R.id.webview56);
        webview57 = findViewById(R.id.webview57);
        webview58 = findViewById(R.id.webview58);
        webview59 = findViewById(R.id.webview59);
        webview60 = findViewById(R.id.webview60);
        webview61 = findViewById(R.id.webview61);
        webview62 = findViewById(R.id.webview62);
        webview63 = findViewById(R.id.webview63);
        webview64 = findViewById(R.id.webview64);
        webview65 = findViewById(R.id.webview65);
        webview66 = findViewById(R.id.webview66);
        webview67 = findViewById(R.id.webview67);
        webview68 = findViewById(R.id.webview68);
        webview69 = findViewById(R.id.webview69);
        webview70 = findViewById(R.id.webview70);
        webview71 = findViewById(R.id.webview71);
        webview72 = findViewById(R.id.webview72);
        webview73 = findViewById(R.id.webview73);
        webview74 = findViewById(R.id.webview74);
        webview75 = findViewById(R.id.webview75);
        webview76 = findViewById(R.id.webview76);
        webview77 = findViewById(R.id.webview77);
        webview78 = findViewById(R.id.webview78);
        webview79 = findViewById(R.id.webview79);
        webview80 = findViewById(R.id.webview80);
        webview81 = findViewById(R.id.webview81);
        webview82 = findViewById(R.id.webview82);
        webview83 = findViewById(R.id.webview83);
        webview84 = findViewById(R.id.webview84);
        webview85 = findViewById(R.id.webview85);
        webview86 = findViewById(R.id.webview86);
        webview87 = findViewById(R.id.webview87);
        webview88 = findViewById(R.id.webview88);
        webview89 = findViewById(R.id.webview89);
        webview90 = findViewById(R.id.webview90);
        webview91 = findViewById(R.id.webview91);
        webview92 = findViewById(R.id.webview92);
        webview93 = findViewById(R.id.webview93);
        webview94 = findViewById(R.id.webview94);
        webview95 = findViewById(R.id.webview95);
        webview96 = findViewById(R.id.webview96);
        webview97 = findViewById(R.id.webview97);
        webview98 = findViewById(R.id.webview98);
        webview99 = findViewById(R.id.webview99);
        webview100 = findViewById(R.id.webview100);

                setupWebView(webview1);
        setupWebView(webview2);
        setupWebView(webview3);
        setupWebView(webview4);
        setupWebView(webview5);
        setupWebView(webview6);
        setupWebView(webview7);
        setupWebView(webview8);
        setupWebView(webview9);
        setupWebView(webview10);
        setupWebView(webview11);
        setupWebView(webview12);
        setupWebView(webview13);
        setupWebView(webview14);
        setupWebView(webview15);
        setupWebView(webview16);
        setupWebView(webview17);
        setupWebView(webview18);
        setupWebView(webview19);
        setupWebView(webview20);
        setupWebView(webview21);
        setupWebView(webview22);
        setupWebView(webview23);
        setupWebView(webview24);
        setupWebView(webview25);
        setupWebView(webview26);
        setupWebView(webview27);
        setupWebView(webview28);
        setupWebView(webview29);
        setupWebView(webview30);
        setupWebView(webview31);
        setupWebView(webview32);
        setupWebView(webview33);
        setupWebView(webview34);
        setupWebView(webview35);
        setupWebView(webview36);
        setupWebView(webview37);
        setupWebView(webview38);
        setupWebView(webview39);
        setupWebView(webview40);
        setupWebView(webview41);
        setupWebView(webview42);
        setupWebView(webview43);
        setupWebView(webview44);
        setupWebView(webview45);
        setupWebView(webview46);
        setupWebView(webview47);
        setupWebView(webview48);
        setupWebView(webview49);
        setupWebView(webview50);
        setupWebView(webview51);
        setupWebView(webview52);
        setupWebView(webview53);
        setupWebView(webview54);
        setupWebView(webview55);
        setupWebView(webview56);
        setupWebView(webview57);
        setupWebView(webview58);
        setupWebView(webview59);
        setupWebView(webview60);
        setupWebView(webview61);
        setupWebView(webview62);
        setupWebView(webview63);
        setupWebView(webview64);
        setupWebView(webview65);
        setupWebView(webview66);
        setupWebView(webview67);
        setupWebView(webview68);
        setupWebView(webview69);
        setupWebView(webview70);
        setupWebView(webview71);
        setupWebView(webview72);
        setupWebView(webview73);
        setupWebView(webview74);
        setupWebView(webview75);
        setupWebView(webview76);
        setupWebView(webview77);
        setupWebView(webview78);
        setupWebView(webview79);
        setupWebView(webview80);
        setupWebView(webview81);
        setupWebView(webview82);
        setupWebView(webview83);
        setupWebView(webview84);
        setupWebView(webview85);
        setupWebView(webview86);
        setupWebView(webview87);
        setupWebView(webview88);
        setupWebView(webview89);
        setupWebView(webview90);
        setupWebView(webview91);
        setupWebView(webview92);
        setupWebView(webview93);
        setupWebView(webview94);
        setupWebView(webview95);
        setupWebView(webview96);
        setupWebView(webview97);
        setupWebView(webview98);
        setupWebView(webview99);
        setupWebView(webview100);
    }

    private void setupWebView(WebView webView) {
        webView.getSettings().setJavaScriptEnabled(true);
        webView.getSettings().setSupportZoom(true);
        webView.setWebViewClient(new WebViewClient());
    }

    private void loadVideos() {
        link = getIntent().getStringExtra("100");
        if (link == null || link.isEmpty()) {
            Toast.makeText(this, "No URL provided", Toast.LENGTH_SHORT).show();
            return;
        }

                webview1.loadUrl(link);
        webview2.loadUrl(link);
        webview3.loadUrl(link);
        webview4.loadUrl(link);
        webview5.loadUrl(link);
        webview6.loadUrl(link);
        webview7.loadUrl(link);
        webview8.loadUrl(link);
        webview9.loadUrl(link);
        webview10.loadUrl(link);
        webview11.loadUrl(link);
        webview12.loadUrl(link);
        webview13.loadUrl(link);
        webview14.loadUrl(link);
        webview15.loadUrl(link);
        webview16.loadUrl(link);
        webview17.loadUrl(link);
        webview18.loadUrl(link);
        webview19.loadUrl(link);
        webview20.loadUrl(link);
        webview21.loadUrl(link);
        webview22.loadUrl(link);
        webview23.loadUrl(link);
        webview24.loadUrl(link);
        webview25.loadUrl(link);
        webview26.loadUrl(link);
        webview27.loadUrl(link);
        webview28.loadUrl(link);
        webview29.loadUrl(link);
        webview30.loadUrl(link);
        webview31.loadUrl(link);
        webview32.loadUrl(link);
        webview33.loadUrl(link);
        webview34.loadUrl(link);
        webview35.loadUrl(link);
        webview36.loadUrl(link);
        webview37.loadUrl(link);
        webview38.loadUrl(link);
        webview39.loadUrl(link);
        webview40.loadUrl(link);
        webview41.loadUrl(link);
        webview42.loadUrl(link);
        webview43.loadUrl(link);
        webview44.loadUrl(link);
        webview45.loadUrl(link);
        webview46.loadUrl(link);
        webview47.loadUrl(link);
        webview48.loadUrl(link);
        webview49.loadUrl(link);
        webview50.loadUrl(link);
        webview51.loadUrl(link);
        webview52.loadUrl(link);
        webview53.loadUrl(link);
        webview54.loadUrl(link);
        webview55.loadUrl(link);
        webview56.loadUrl(link);
        webview57.loadUrl(link);
        webview58.loadUrl(link);
        webview59.loadUrl(link);
        webview60.loadUrl(link);
        webview61.loadUrl(link);
        webview62.loadUrl(link);
        webview63.loadUrl(link);
        webview64.loadUrl(link);
        webview65.loadUrl(link);
        webview66.loadUrl(link);
        webview67.loadUrl(link);
        webview68.loadUrl(link);
        webview69.loadUrl(link);
        webview70.loadUrl(link);
        webview71.loadUrl(link);
        webview72.loadUrl(link);
        webview73.loadUrl(link);
        webview74.loadUrl(link);
        webview75.loadUrl(link);
        webview76.loadUrl(link);
        webview77.loadUrl(link);
        webview78.loadUrl(link);
        webview79.loadUrl(link);
        webview80.loadUrl(link);
        webview81.loadUrl(link);
        webview82.loadUrl(link);
        webview83.loadUrl(link);
        webview84.loadUrl(link);
        webview85.loadUrl(link);
        webview86.loadUrl(link);
        webview87.loadUrl(link);
        webview88.loadUrl(link);
        webview89.loadUrl(link);
        webview90.loadUrl(link);
        webview91.loadUrl(link);
        webview92.loadUrl(link);
        webview93.loadUrl(link);
        webview94.loadUrl(link);
        webview95.loadUrl(link);
        webview96.loadUrl(link);
        webview97.loadUrl(link);
        webview98.loadUrl(link);
        webview99.loadUrl(link);
        webview100.loadUrl(link);
    }

    @Override
    public void onBackPressed() {
        Intent intent = new Intent(this, HomeActivity.class);
        startActivity(intent);
        finish();
    }
}
